version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: resume_analyzer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sonu@801
      POSTGRES_DB: resume_analyzer_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume_analyzer_backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sonu@801
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=resume_analyzer_db
      - SECRET_KEY=9e8a71c42f0b4d21e8a93019d1e34a6b29f0e1d2c3b4a567890abcdef123456
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume_analyzer_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  pgdata:
